
"""
junction_trimmer_v1.py

Geometry utilities to trim crack-face polylines around multi-branch junctions (degree > 2).

Intent
------
When using a "core" junction model, reconstructed crack faces (upper/lower) can overlap or
intersect near a junction vertex because each branch is plotted independently.

This module trims faces locally so that, in a cyclic ordering around a vertex v:

    lower_face(branch j) meets upper_face(branch j+1)

at a single point (their intersection), producing a polygonal "gap" around the junction.

Design principles
-----------------
- Purely a plotting/post-processing fix: does NOT change solver state.
- Local: only modifies the first few segments near the junction.
- Robust: works for polylines (piecewise linear), handles near-parallel cases gracefully.

Typical use
-----------
You must supply, for a given vertex, per-incident branch:
- a midline polyline P (for angle ordering),
- upper face polyline U,
- lower face polyline L,
- and whether the arrays start at the vertex or end at the vertex.

Then call trim_faces_at_junction(...). You can integrate this in your plotter right before ax.plot().

Author: generated by ChatGPT
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Tuple, Optional
import math
import numpy as np


@dataclass
class BranchFaces:
    """Container for one incident branch at a junction."""
    pid: int
    P: np.ndarray          # (N,2) midline
    U: np.ndarray          # (N,2) upper face
    L: np.ndarray          # (N,2) lower face
    start_at_vertex: bool = True


_EPS = 1e-14


def _as_xy(a: np.ndarray) -> np.ndarray:
    a = np.asarray(a, float)
    if a.ndim != 2 or a.shape[1] != 2:
        raise ValueError(f"Expected array (N,2), got {a.shape}")
    return a


def angle_of_vector(v: np.ndarray) -> float:
    return math.atan2(float(v[1]), float(v[0]))


def line_intersection_ray_ray(
    p: np.ndarray, r: np.ndarray, q: np.ndarray, s: np.ndarray
) -> Tuple[Optional[np.ndarray], float, float]:
    """Intersect rays p+t r and q+u s with t>=0, u>=0."""
    p = np.asarray(p, float); r = np.asarray(r, float)
    q = np.asarray(q, float); s = np.asarray(s, float)
    A = np.column_stack([r, -s])  # 2x2
    det = float(np.linalg.det(A))
    if abs(det) < 1e-12:
        return None, float("nan"), float("nan")
    rhs = (q - p)
    t, u = np.linalg.solve(A, rhs)
    x = p + t * r
    return x, float(t), float(u)


def closest_point_on_segment(a: np.ndarray, b: np.ndarray, p: np.ndarray) -> Tuple[np.ndarray, float]:
    a = np.asarray(a, float); b = np.asarray(b, float); p = np.asarray(p, float)
    ab = b - a
    denom = float(np.dot(ab, ab))
    if denom < _EPS:
        return a.copy(), 0.0
    tau = float(np.dot(p - a, ab) / denom)
    tau = max(0.0, min(1.0, tau))
    cp = a + tau * ab
    return cp, tau


def trim_polyline_to_point(poly: np.ndarray, point: np.ndarray, search_segments: int = 10) -> np.ndarray:
    """Trim polyline so it starts at `point` (inserted on nearest of first segments)."""
    poly = _as_xy(poly)
    point = np.asarray(point, float)

    n = poly.shape[0]
    if n < 2:
        out = poly.copy()
        if n == 1:
            out[0] = point
        return out

    m = min(search_segments, n - 1)
    best_d = float("inf")
    best_i = 0
    best_cp = poly[0].copy()

    for i in range(m):
        cp, _ = closest_point_on_segment(poly[i], poly[i + 1], point)
        d = float(np.linalg.norm(cp - point))
        if d < best_d:
            best_d = d
            best_i = i
            best_cp = cp

    # Start at requested point (not best_cp) to ensure consistent joins
    tail = poly[best_i + 1 :].copy()
    out = np.vstack([point[None, :], tail])
    return out


def _ensure_start_at_vertex(b: BranchFaces) -> BranchFaces:
    P = _as_xy(b.P); U = _as_xy(b.U); L = _as_xy(b.L)
    if b.start_at_vertex:
        return BranchFaces(pid=b.pid, P=P, U=U, L=L, start_at_vertex=True)
    return BranchFaces(pid=b.pid, P=P[::-1].copy(), U=U[::-1].copy(), L=L[::-1].copy(), start_at_vertex=True)


def order_incident_by_midline_angle(vertex_xy: np.ndarray, branches: List[BranchFaces], look_ahead: int = 3) -> List[BranchFaces]:
    v = np.asarray(vertex_xy, float)
    items = []
    for b in branches:
        bb = _ensure_start_at_vertex(b)
        P = bb.P
        if P.shape[0] < 2:
            ang = 0.0
        else:
            k = min(max(1, look_ahead), P.shape[0] - 1)
            d = P[k] - P[0]
            ang = angle_of_vector(d)
        items.append((ang, bb))
    items.sort(key=lambda t: t[0])
    return [bb for _, bb in items]


def trim_faces_at_junction(
    vertex_xy: np.ndarray,
    branches: List[BranchFaces],
    look_ahead: int = 3,
    search_segments: int = 10,
    parallel_fallback: str = "average",
) -> Tuple[List[BranchFaces], np.ndarray]:
    """Trim faces so lower(j) meets upper(j+1) cyclically."""
    v = np.asarray(vertex_xy, float)
    if len(branches) < 3:
        ordered = [_ensure_start_at_vertex(b) for b in branches]
        return ordered, np.zeros((0, 2), float)

    ordered = order_incident_by_midline_angle(v, branches, look_ahead=look_ahead)
    trimmed = [BranchFaces(pid=b.pid, P=b.P.copy(), U=b.U.copy(), L=b.L.copy(), start_at_vertex=True) for b in ordered]
    m = len(trimmed)
    gap_pts = np.zeros((m, 2), float)

    for j in range(m):
        bj = trimmed[j]
        bn = trimmed[(j + 1) % m]

        Lj = bj.L
        Un = bn.U

        if Lj.shape[0] < 2 or Un.shape[0] < 2:
            x = v.copy()
        else:
            r = Lj[1] - Lj[0]
            s = Un[1] - Un[0]
            x, t, u = line_intersection_ray_ray(Lj[0], r, Un[0], s)
            if x is None or not (np.isfinite(t) and np.isfinite(u)) or t < 0.0 or u < 0.0:
                if parallel_fallback == "average":
                    x = 0.5 * (Lj[1] + Un[1])
                else:
                    x = v.copy()

        gap_pts[j] = x

        bj.L = trim_polyline_to_point(bj.L, x, search_segments=search_segments)
        bn.U = trim_polyline_to_point(bn.U, x, search_segments=search_segments)

    return trimmed, gap_pts
