
"""
dce_plots_v2.py
Plotting utilities for v2 solver/results.

Key features:
- Uses ONLY numerical fields (no analytical LEFM/Williams).
- Saves all figures to a user-specified directory (save_dir).
- Stress component contour plots in GLOBAL coordinates with banded filled contours + labeled contour lines.
- Undeformed crack line shown as thin dotted line in all relevant plots.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Optional, Tuple

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import Normalize, LogNorm, SymLogNorm


def _sample_x_local(a: float, n: int = 1200, eps_factor: float = 1e-6) -> np.ndarray:
    eps = max(float(eps_factor) * float(a), 1e-18)
    return np.linspace(-a + eps, a - eps, int(n))


def _robust_symmetric_limit(z: np.ndarray, clip_percentile: float = 99.5) -> float:
    z = np.asarray(z, float).ravel()
    z = z[np.isfinite(z)]
    if z.size == 0:
        return 1.0
    m = np.percentile(np.abs(z), float(clip_percentile))
    return float(m) if m > 0 else float(np.max(np.abs(z)) + 1e-16)


def _ensure_dir(d: Optional[Path]) -> Optional[Path]:
    if d is None:
        return None
    d = Path(d)
    d.mkdir(parents=True, exist_ok=True)
    return d


@dataclass
class StressPlotOpts:
    # Domain / resolution
    extent_factor: float = 1.5
    n_grid: int = 301
    xlim: Optional[Tuple[float, float]] = None  # meters
    ylim: Optional[Tuple[float, float]] = None  # meters

    # Physics
    add_remote: bool = True
    mask_crack: bool = True
    overlay_deformed: bool = True

    # Color scaling
    vmax_factor: float = 10.0           # vmax = vmax_factor * |sigma_ref|
    vref_component: str = "syy"         # "sxx"|"syy"|"sxy" (uses remote component as reference)
    vmax_mpa: Optional[float] = None    # explicit cap in MPa (overrides vmax_factor)
    n_bands: int = 15

    # Normalization: "linear" | "log" | "symlog"
    norm: str = "symlog"
    symlog_linthresh_mpa: Optional[float] = None

    # Styling
    cmap: str = "jet"
    label_contours: bool = True
    label_fmt: str = "%.0f"

    # Saving
    file_prefix: str = "stress"


class DCEPlotterV2:
    """
    V2 plotter operating on a DCEResultsV2 object.

    Parameters
    ----------
    results : DCEResultsV2
        Results object from utils.dce_results_v2
    save_dir : str or Path or None
        If provided, all figures generated by this plotter will be saved as PNGs.
    """
    def __init__(self, results, save_dir: Optional[str | Path] = None, *, out_dir: Optional[str | Path] = None):
        self.results = results
        self.calc = results.calc
        # solution dict stored under .sol in v1-style results
        self.sol = getattr(results, "sol", None)
        if self.sol is None:
            self.sol = getattr(results, "solution", None)
        if self.sol is None:
            raise TypeError("DCEPlotterV2 expects a results object with a .sol (solution dict).")
        # Backward/forward compatible naming: allow either save_dir or out_dir.
        if save_dir is None and out_dir is not None:
            save_dir = out_dir
        self.save_dir = _ensure_dir(save_dir)

    def _save(self, fig: plt.Figure, name: str) -> None:
        if self.save_dir is None:
            return
        path = self.save_dir / f"{name}.png"
        fig.savefig(path, dpi=200, bbox_inches="tight")

    # -------------------------
    # Primary plots
    # -------------------------
    def plot_burgers(self, n: int = 1200, eps_factor: float = 1e-6, clip_percentile: float = 99.5):
        a = float(self.calc.crack.half_length)
        x = _sample_x_local(a, n=n, eps_factor=eps_factor)

        bI = self.calc.evaluate_b_mode(x, self.sol, mode="I")
        bII = self.calc.evaluate_b_mode(x, self.sol, mode="II")

        fig, axs = plt.subplots(1, 2, figsize=(12, 4), constrained_layout=True)
        for ax, b, title in [(axs[0], bI, "Mode I  b(x)"), (axs[1], bII, "Mode II  b(x)")]:
            lim = _robust_symmetric_limit(b, clip_percentile=clip_percentile)
            ax.plot(x, b, lw=1.5)
            ax.set_title(title)
            ax.set_xlabel("x (local) [m]")
            ax.set_ylabel("b(x) [-]")
            ax.grid(True, alpha=0.25)
            ax.set_ylim(-lim, lim)

            # crack line (undeformed) shown as dotted thin line at y=0 for reference
            ax.axhline(0.0, ls=":", lw=1.0)

        self._save(fig, "burgers")
        return fig

    def plot_cod_csd(self, n_theta: int = 12000):
        x, COD, CSD = self.results.reconstruct_cod_csd(n_theta=n_theta, enforce_tip_zero=True)

        fig, axs = plt.subplots(1, 2, figsize=(12, 4), constrained_layout=True)
        axs[0].plot(x, COD, lw=1.8)
        axs[1].plot(x, CSD, lw=1.8)

        for ax, title in [(axs[0], "COD(x)"), (axs[1], "CSD(x)")]:
            ax.set_title(title)
            ax.set_xlabel("x (local) [m]")
            ax.set_ylabel("displacement [m]")
            ax.grid(True, alpha=0.25)
            ax.axhline(0.0, ls=":", lw=1.0)

        self._save(fig, "cod_csd")
        return fig

    def plot_crack_geometry(self, n_theta: int = 12000, scale: float = 1.0):
        """
        Plot undeformed crack line + deformed upper/lower faces in GLOBAL coordinates.
        """
        a = float(self.calc.crack.half_length)
        x, COD, CSD = self.results.reconstruct_cod_csd(n_theta=n_theta, enforce_tip_zero=True)

        # local displacements (upper face)
        u1 = 0.5 * CSD * float(scale)
        u2 = 0.5 * COD * float(scale)

        # lower face is negative
        u1m = -u1
        u2m = -u2

        # local coordinates of points along crack
        xl = x
        yl = np.zeros_like(xl)

        # rotate+translate to global
        R = self.calc.R
        c = np.asarray(self.calc.crack.center, float).reshape(2,)

        P0 = (R @ np.vstack([xl, yl])).T + c
        Pp = (R @ np.vstack([xl + u1, yl + u2])).T + c
        Pm = (R @ np.vstack([xl + u1m, yl + u2m])).T + c

        # Plot with mixed units for readability: x in mm, y in microns.
        x0 = P0[:, 0] * 1e3
        y0 = P0[:, 1] * 1e6
        xp = Pp[:, 0] * 1e3
        yp = Pp[:, 1] * 1e6
        xm = Pm[:, 0] * 1e3
        ym = Pm[:, 1] * 1e6

        fig, ax = plt.subplots(1, 1, figsize=(8.0, 3.2), constrained_layout=True)
        ax.plot(x0, y0, ls=":", lw=1.0, color="k", label="crack (undeformed)")
        ax.plot(xp, yp, lw=1.5, label="upper face")
        ax.plot(xm, ym, lw=1.5, label="lower face")
        ax.set_title("Crack geometry (global)")
        ax.set_xlabel("x [mm]")
        ax.set_ylabel("y [µm]")
        ax.ticklabel_format(axis="y", style="plain")
        ax.grid(True, alpha=0.25)
        ax.legend(loc="best")

        # Make sure the y-axis is not visually collapsed.
        y_all = [y0, yp, ym]
        y_min = min(float(arr.min()) for arr in y_all)
        y_max = max(float(arr.max()) for arr in y_all)
        y_span = max(y_max - y_min, 1e-12)
        pad = 0.15 * y_span
        ax.set_ylim(y_min - pad, y_max + pad)

        self._save(fig, "crack_geometry")
        return fig

    # -------------------------
    # Stress fields (GLOBAL)
    # -------------------------
    def plot_stress_components_global(self, opts: StressPlotOpts, components: Iterable[str] = ("sxx","syy","sxy")):
        """
        Numerical stress components in GLOBAL coordinates around the crack.

        Returns a dict comp->figure
        """
        opts = opts if isinstance(opts, StressPlotOpts) else StressPlotOpts(**dict(opts))
        a = float(self.calc.crack.half_length)

        # Domain in GLOBAL coordinates
        if opts.xlim is not None:
            xmin, xmax = opts.xlim
        else:
            xmin, xmax = -opts.extent_factor * a, +opts.extent_factor * a
        if opts.ylim is not None:
            ymin, ymax = opts.ylim
        else:
            ymin, ymax = -opts.extent_factor * a, +opts.extent_factor * a

        n = int(opts.n_grid)
        xg = np.linspace(xmin, xmax, n)
        yg = np.linspace(ymin, ymax, n)
        Xg, Yg = np.meshgrid(xg, yg)

        # map global -> local for stress evaluation
        R = self.calc.R
        center = np.asarray(self.calc.crack.center, float).reshape(2,)
        Rt = R.T
        Pl = (Rt @ (np.vstack([Xg.ravel(), Yg.ravel()]) - center.reshape(2,1))).reshape(2, *Xg.shape)
        Xl, Yl = Pl[0], Pl[1]

        # optional masking: remove immediate crack-line neighborhood to avoid singular pixels
        if opts.mask_crack:
            # small band around y=0 and within crack projection
            band = 5e-4 * a
            mask = (np.abs(Yl) < band) & (np.abs(Xl) <= a)
        else:
            mask = np.zeros_like(Xl, dtype=bool)

        # compute local stresses numerically [Pa]
        s11, s22, s12 = self.calc.evaluate_stress_field_local(Xl, Yl, self.sol, add_remote=bool(opts.add_remote))

        # rotate stress tensor to global: Sg = R * Sl * R^T
        # components: sxx, syy, sxy
        sxx = R[0,0]**2 * s11 + 2*R[0,0]*R[0,1]*s12 + R[0,1]**2 * s22
        syy = R[1,0]**2 * s11 + 2*R[1,0]*R[1,1]*s12 + R[1,1]**2 * s22
        sxy = R[0,0]*R[1,0]*s11 + (R[0,0]*R[1,1] + R[0,1]*R[1,0])*s12 + R[0,1]*R[1,1]*s22

        # convert to MPa for plotting
        S = {"sxx": sxx/1e6, "syy": syy/1e6, "sxy": sxy/1e6}
        for k in S:
            Z = np.asarray(S[k])
            Z = np.where(mask, np.nan, Z)
            S[k] = Z

        # choose reference for vmax
        remote = self.calc.get_applied_stress_global()
        # reference components in MPa
        ref_map = {"sxx": remote[0,0]/1e6, "syy": remote[1,1]/1e6, "sxy": remote[0,1]/1e6}
        sref = float(abs(ref_map.get(str(opts.vref_component).lower(), remote[1,1]/1e6)))
        if sref <= 0:
            sref = float(np.nanmax(np.abs(S.get("syy")))) if np.isfinite(np.nanmax(np.abs(S.get("syy")))) else 1.0
        vmax = float(opts.vmax_mpa) if opts.vmax_mpa is not None else float(opts.vmax_factor) * sref
        vmax = max(vmax, 1e-12)

        # set normalization
        norm_kind = (opts.norm or "linear").lower()
        if norm_kind == "log":
            norm = LogNorm(vmin=max(vmax/1e3, 1e-6), vmax=vmax)
        elif norm_kind == "symlog":
            lin = opts.symlog_linthresh_mpa
            if lin is None:
                lin = 0.02 * vmax
            lin = max(float(lin), 1e-9)
            norm = SymLogNorm(linthresh=lin, vmin=-vmax, vmax=vmax)
        else:
            norm = Normalize(vmin=-vmax, vmax=vmax)

        levels = np.linspace(-vmax, vmax, int(opts.n_bands) + 1)

        figs = {}
        for comp in components:
            comp = str(comp).lower()
            if comp not in S:
                continue
            Z = S[comp]

            fig, ax = plt.subplots(1, 1, figsize=(7.2, 6.0), constrained_layout=True)
            cf = ax.contourf(Xg, Yg, Z, levels=levels, cmap=opts.cmap, norm=norm, extend="both")
            cs = ax.contour(Xg, Yg, Z, levels=levels, colors="k", linewidths=0.6, alpha=0.55)
            if opts.label_contours:
                ax.clabel(cs, inline=True, fontsize=8, fmt=opts.label_fmt)

            # undeformed crack (dotted thin)
            # build endpoints in global
            pL = (R @ np.array([-a, 0.0])) + center
            pR = (R @ np.array([+a, 0.0])) + center
            ax.plot([pL[0], pR[0]], [pL[1], pR[1]], ls=":", lw=1.0, color="k")

            # overlay deformed crack faces if requested
            if opts.overlay_deformed:
                # use geometry points from reconstruct_cod_csd
                x_local, COD, CSD = self.results.reconstruct_cod_csd(n_theta=6000, enforce_tip_zero=True)
                u1 = 0.5 * CSD
                u2 = 0.5 * COD
                xl = x_local
                yl = np.zeros_like(xl)

                Pup = (R @ np.vstack([xl + u1, yl + u2])).T + center
                Plw = (R @ np.vstack([xl - u1, yl - u2])).T + center
                ax.plot(Pup[:,0], Pup[:,1], lw=1.0)
                ax.plot(Plw[:,0], Plw[:,1], lw=1.0)

            ax.set_aspect("equal", adjustable="box")
            ax.set_xlabel("x [m]")
            ax.set_ylabel("y [m]")
            ax.set_title(f"{comp} [MPa]  (vmax={vmax:.1f} MPa)")

            cb = fig.colorbar(cf, ax=ax, shrink=0.85)
            cb.set_label("Stress [MPa]")

            name = f"{opts.file_prefix}_{comp}"
            self._save(fig, name)
            figs[comp] = fig

        return figs


# Backward compatible alias (if any older cells expect V0)
DCEPlotterV0 = DCEPlotterV2


