"""CLI: overwrite the CRACK_NETWORK sheet of a case workbook with a random
distribution of straight cracks generated by
`fracture_utils.Ugenerator.random_straight_cracks`.

Other sheets in the workbook (BEM, GEOMETRY, CONFIGURATION_*) are left
untouched. The disk radius is read from the BEM sheet and used as the
default containment domain (`--domain disk`); pass `--domain rect` with
`--rect-w/--rect-h` for a rectangular domain instead.

Example:

    python input/seed_crack_network.py disk_compression_2.xlsx \\
        --n 20 --mean-mm 2 --std-mm 4 --seed 0
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from openpyxl import load_workbook

_HERE = Path(__file__).resolve().parent
_REPO_ROOT = _HERE.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from fracture_utils.Ugenerator import random_straight_cracks  # noqa: E402


def _read_disk_radius(xlsx_path: Path) -> float:
    df = pd.read_excel(xlsx_path, sheet_name="BEM")
    row = df.loc[df["key"].astype(str).str.strip() == "R_m"]
    if row.empty:
        raise SystemExit(f"BEM sheet of {xlsx_path} has no key 'R_m'")
    return float(row["value"].iloc[0])


def _overwrite_crack_network_sheet(
    xlsx_path: Path,
    vertices: np.ndarray,
    edges: np.ndarray,
) -> None:
    """Replace only the CRACK_NETWORK sheet, preserving sheet order."""
    wb = load_workbook(xlsx_path)
    sheet_order = list(wb.sheetnames)
    if "CRACK_NETWORK" in wb.sheetnames:
        idx = sheet_order.index("CRACK_NETWORK")
        del wb["CRACK_NETWORK"]
    else:
        idx = len(sheet_order)
    ws = wb.create_sheet("CRACK_NETWORK", index=idx)

    # Vertices: cols A-C
    ws.cell(row=1, column=1, value="id")
    ws.cell(row=1, column=2, value="x_m")
    ws.cell(row=1, column=3, value="y_m")
    for i, (vid, x, y) in enumerate(vertices, start=2):
        ws.cell(row=i, column=1, value=int(vid))
        ws.cell(row=i, column=2, value=float(x))
        ws.cell(row=i, column=3, value=float(y))

    # Edges: cols E-F
    ws.cell(row=1, column=5, value="v0")
    ws.cell(row=1, column=6, value="v1")
    for i, (v0, v1) in enumerate(edges, start=2):
        ws.cell(row=i, column=5, value=int(v0))
        ws.cell(row=i, column=6, value=int(v1))

    wb.save(xlsx_path)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("xlsx", type=Path, help="case workbook (relative paths resolve to input/)")
    ap.add_argument("--n", type=int, default=20, help="number of cracks (default: 20)")
    ap.add_argument("--mean-mm", type=float, default=2.0, help="length mean [mm]")
    ap.add_argument("--std-mm", type=float, default=4.0, help="length stddev [mm]")
    ap.add_argument("--min-mm", type=float, default=0.1, help="length lower truncation [mm]")
    ap.add_argument("--max-mm", type=float, default=None, help="length upper truncation [mm]")
    ap.add_argument("--margin-mm", type=float, default=0.5, help="boundary margin [mm]")
    ap.add_argument("--domain", choices=("disk", "rect"), default="disk")
    ap.add_argument("--rect-w-mm", type=float, default=None, help="rect domain width [mm]")
    ap.add_argument("--rect-h-mm", type=float, default=None, help="rect domain height [mm]")
    ap.add_argument("--angle-lo-deg", type=float, default=0.0)
    ap.add_argument("--angle-hi-deg", type=float, default=180.0)
    ap.add_argument("--seed", type=int, default=None)
    args = ap.parse_args(argv)

    xlsx_path = args.xlsx if args.xlsx.is_absolute() else (_HERE / args.xlsx)
    xlsx_path = xlsx_path.resolve()
    if not xlsx_path.is_file():
        raise SystemExit(f"workbook not found: {xlsx_path}")

    mm = 1.0e-3
    if args.domain == "disk":
        R = _read_disk_radius(xlsx_path)
        domain_size: float | tuple[float, float] = R
        print(f"[domain] disk R={R*1e3:.3f} mm (from BEM.R_m)")
    else:
        if args.rect_w_mm is None or args.rect_h_mm is None:
            raise SystemExit("--domain rect requires --rect-w-mm and --rect-h-mm")
        domain_size = (args.rect_w_mm * mm, args.rect_h_mm * mm)
        print(f"[domain] rect {args.rect_w_mm}x{args.rect_h_mm} mm")

    vertices, edges = random_straight_cracks(
        n_cracks=args.n,
        length_mean=args.mean_mm * mm,
        length_std=args.std_mm * mm,
        domain_shape=args.domain,
        domain_size=domain_size,
        length_min=args.min_mm * mm,
        length_max=(args.max_mm * mm) if args.max_mm is not None else None,
        angle_range_deg=(args.angle_lo_deg, args.angle_hi_deg),
        margin=args.margin_mm * mm,
        seed=args.seed,
    )

    if len(edges) == 0:
        raise SystemExit("no cracks generated -- check domain/length settings")

    print(f"[generated] {len(edges)} cracks, {len(vertices)} vertices")
    print(f"[lengths]   min={_lengths_mm(vertices, edges).min():.3f} mm, "
          f"max={_lengths_mm(vertices, edges).max():.3f} mm, "
          f"mean={_lengths_mm(vertices, edges).mean():.3f} mm")

    _overwrite_crack_network_sheet(xlsx_path, vertices, edges)
    print(f"[wrote]     CRACK_NETWORK sheet of {xlsx_path}")
    return 0


def _lengths_mm(vertices: np.ndarray, edges: np.ndarray) -> np.ndarray:
    xy = vertices[:, 1:3]
    p0 = xy[edges[:, 0]]
    p1 = xy[edges[:, 1]]
    return np.linalg.norm(p1 - p0, axis=1) * 1e3


if __name__ == "__main__":
    raise SystemExit(main())
